name: example
description: flutter_pcm_sound example app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_pcm_sound:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
