name: flutter_pcm_sound
description: Send real-time PCM audio (16-bit integer) to your device speakers
version: 3.1.2
homepage: https://github.com/chipweinberger/flutter_pcm_sound

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  web: ^1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_pcm_sound
        pluginClass: FlutterPcmSoundPlugin
      ios:
        pluginClass: FlutterPcmSoundPlugin
      macos:
        pluginClass: FlutterPcmSoundPlugin
      web:
        pluginClass: FlutterPcmSoundWeb
        fileName: flutter_pcm_sound_web.dart